ShopOnline/Areas/Admin/Controllers/SachController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ShopOnline.Models;

namespace ShopOnline.Areas.Admin.Controllers
{
	public class SachController : Controller
	{
		private ShopOnlineEntities db = new ShopOnlineEntities();

		// GET: Sach
		public ActionResult Index()
		{
			var sach = db.Sach.Include(s => s.LoaiSach).Include(s => s.NhaXuatBan);
			return View(sach.ToList());
		}

		// GET: Sach/Create
		public ActionResult Create()
		{
			ViewBag.LoaiSach_ID = new SelectList(db.LoaiSach, "ID", "TenLoai");
			ViewBag.NhaXuatBan_ID = new SelectList(db.NhaXuatBan, "ID", "TenNhaXuatBan");
			ModelState.AddModelError("UploadError", "");
			return View();
		}

		// POST: Sach/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Create([Bind(Include = "ID,NhaXuatBan_ID,LoaiSach_ID,TenSach,DonGia,SoLuong,DuLieuHinhAnhBia,MoTa")] Sach sach)
		{
			ViewBag.LoaiSach_ID = new SelectList(db.LoaiSach, "ID", "TenLoai", sach.LoaiSach_ID);
			ViewBag.NhaXuatBan_ID = new SelectList(db.NhaXuatBan, "ID", "TenNhaXuatBan", sach.NhaXuatBan_ID);

			if (ModelState.IsValid)
			{
				// Upload
				if (sach.DuLieuHinhAnhBia != null)
				{
					string folder = "Storage/";
					string fileExtension = Path.GetExtension(sach.DuLieuHinhAnhBia.FileName).ToLower();

					// Kiểm tra kiểu
					var fileTypeSupported = new[] { ".jpg", ".jpeg", ".png", ".gif" };
					if (!fileTypeSupported.Contains(fileExtension))
					{
						ModelState.AddModelError("UploadError", "Chỉ cho phép tập tin JPG, PNG, GIF!");
						return View(sach);
					}
					else if (sach.DuLieuHinhAnhBia.ContentLength > 2 * 1024 * 1024)
					{
						ModelState.AddModelError("UploadError", "Chỉ cho phép tập tin từ 2MB trở xuống!");
						return View(sach);
					}
					else
					{
						string fileName = Guid.NewGuid().ToString() + fileExtension;
						string filePath = Path.Combine(Server.MapPath("~/" + folder), fileName);
						sach.DuLieuHinhAnhBia.SaveAs(filePath);

						// Cập nhật đường dẫn vào CSDL
						sach.HinhAnhBia = folder + fileName;

						db.Sach.Add(sach);
						db.SaveChanges();
						return RedirectToAction("Index");
					}
				}
				else
				{
					ModelState.AddModelError("UploadError", "Hình ảnh bìa không được bỏ trống!");
					return View(sach);
				}
			}

			return View(sach);
		}

		// GET: Sach/Edit/5
		public ActionResult Edit(int? id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			Sach sach = db.Sach.Find(id);
			if (sach == null)
			{
				return HttpNotFound();
			}
			ViewBag.LoaiSach_ID = new SelectList(db.LoaiSach, "ID", "TenLoai", sach.LoaiSach_ID);
			ViewBag.NhaXuatBan_ID = new SelectList(db.NhaXuatBan, "ID", "TenNhaXuatBan", sach.NhaXuatBan_ID);
			ModelState.AddModelError("UploadError", "");
			return View(sach);
		}

		// POST: Sach/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Edit([Bind(Include = "ID,HinhAnhBia,NhaXuatBan_ID,LoaiSach_ID,TenSach,DonGia,SoLuong,DuLieuHinhAnhBia,MoTa")] Sach sach)
		{
			ViewBag.LoaiSach_ID = new SelectList(db.LoaiSach, "ID", "TenLoai", sach.LoaiSach_ID);
			ViewBag.NhaXuatBan_ID = new SelectList(db.NhaXuatBan, "ID", "TenNhaXuatBan", sach.NhaXuatBan_ID);

			if (ModelState.IsValid)
			{
				// Upload ảnh mới
				if (sach.DuLieuHinhAnhBia != null)
				{
					// Xóa ảnh cũ
					string oldFilePath = Server.MapPath("~/" + sach.HinhAnhBia);
					if (System.IO.File.Exists(oldFilePath)) System.IO.File.Delete(oldFilePath);

					string folder = "Storage/";
					string fileExtension = Path.GetExtension(sach.DuLieuHinhAnhBia.FileName).ToLower();

					// Kiểm tra kiểu
					var fileTypeSupported = new[] { ".jpg", ".jpeg", ".png", ".gif" };
					if (!fileTypeSupported.Contains(fileExtension))
					{
						ModelState.AddModelError("UploadError", "Chỉ cho phép tập tin JPG, PNG, GIF!");
						return View(sach);
					}
					else if (sach.DuLieuHinhAnhBia.ContentLength > 2 * 1024 * 1024)
					{
						ModelState.AddModelError("UploadError", "Chỉ cho phép tập tin từ 2MB trở xuống!");
						return View(sach);
					}
					else
					{
						string fileName = Guid.NewGuid().ToString() + fileExtension;
						string filePath = Path.Combine(Server.MapPath("~/" + folder), fileName);
						sach.DuLieuHinhAnhBia.SaveAs(filePath);

						// Cập nhật đường dẫn vào CSDL
						sach.HinhAnhBia = folder + fileName;

						db.Entry(sach).State = EntityState.Modified;
						db.SaveChanges();
						return RedirectToAction("Index");
					}
				}
				else // Giữ nguyên ảnh cũ
				{
					db.Entry(sach).State = EntityState.Modified;
					db.SaveChanges();
					return RedirectToAction("Index");
				}
			}

			return View(sach);
		}

		// GET: Sach/Delete/5
		public ActionResult Delete(int? id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			Sach sach = db.Sach.Find(id);
			if (sach == null)
			{
				return HttpNotFound();
			}
			return View(sach);
		}

		// POST: Sach/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public ActionResult DeleteConfirmed(int id)
		{
			Sach sach = db.Sach.Find(id);
			db.Sach.Remove(sach);
			db.SaveChanges();
			return RedirectToAction("Index");
		}

		protected override void Dispose(bool disposing)
		{
			if (disposing)
			{
				db.Dispose();
			}
			base.Dispose(disposing);
		}
	}
}

ShopOnline/Areas/AdminTK/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title - Cửa hàng sách</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="container-fluid">
        <nav class="navbar navbar-expand-lg navbar-light" style="background-color:orangered;">
            <a class="navbar-brand" href="@Url.Action("Index", "Home")">
                <img src="~/Images/lg2.png" width="150" height="75" class="d-inline-block align-top" alt="" />
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">Mua nhiều nhất</a>
                    </li>

                    @if (Session["MaThuKho"] == null)
                    {
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("LoginTK","Home")">Đăng nhập</a>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                @Session["HoTenThuKho"].ToString()
                                <span>(Quản lí)</span>
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="@Url.Action("Index", "Sach")">Sách</a>
                                <a class="dropdown-item" href="@Url.Action("Index", "LoaiSach")">Loại sách</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="@Url.Action("Index", "NhaXuatBan")">Nhà xuất bản</a>
                                <a class="dropdown-item" href="@Url.Action("Index", "NhanVien")">Nhân viên</a>
                                <a class="dropdown-item" href="@Url.Action("Index", "KhachHang")">Khách hàng</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="@Url.Action("Index", "ThuKho")">Quản lí</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="@Url.Action("Index", "DatHang")">Đặt hàng</a>
                                <a class="dropdown-item" href="@Url.Action("Index", "DatHang_ChiTiet")">Đặt hàng chi tiết</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="@Url.Action("ChangePassword", "Home")">Đổi mật khẩu</a>
                                <a class="dropdown-item" href="@Url.Action("Logout", "Home")">Đăng xuất</a>
                            </div>
                        </li>
                    }
                </ul>
                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="search" placeholder="Bạn muốn tìm gì?" />
                    <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Tìm kiếm</button>
                </form>
            </div>
        </nav>
    </div>

    <div class="container-fluid body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; Bản quyền @DateTime.Now.Year bởi Nhóm Đồ án - 2.</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>